version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: medCli
    main: ./cmd/main.go
    binary: medCli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: medCli-archive
    # Use the new format syntax (remove the old 'format' key)
    formats:
      - tar.gz
      - zip
    # This is important for file structure
    wrap_in_directory: true
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - config.yaml
      - data/medicine_data.csv
      - install.sh

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  # Remove the deprecated name_template
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Refactors"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: Nexusrex18
    name: medCli
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## medCli {{ .Tag }} ({{ .Date }})

    ### Installation

    **Linux/macOS:**
    ```bash
    curl -fsSL https://raw.githubusercontent.com/Nexusrex18/medCli/main/install.sh | bash
    ```

    **Windows (Git Bash/WSL):**
    ```bash
    bash <(curl -fsSL https://raw.githubusercontent.com/Nexusrex18/medCli/main/install.sh)
    ```

    **Or download the binary directly for your platform below.**
  footer: |
    ---
    **Full Changelog**: https://github.com/Nexusrex18/medCli/compare/{{ .PreviousTag }}...{{ .Tag }}
